### PR TITLE
Make it post to Discord instead of using Twillo

### PR DESCRIPTION
**Pull request by ItsCalebJones**

### CODE REVIEW

**Comment by ItsCalebJones** [comment]
Would probably be better served as a separate branch - or you can take this and make it configurable - up to you.

**Comment by rambosbff** [comment]
I was trying to figure out how to forward it to discord last night, but I haven't used python before, but learned a lot!

**Comment by samuelm2** [comment]
Looks good! We could either keep this on a separate branch, or add a '--useDiscord' flag that would switch it to a discord mode. What do you think?

**Comment by rambosbff** [comment]
> Looks good! We could either keep this on a separate branch, or add a '--useDiscord' flag that would switch it to a discord mode. What do you think?

I'll let you guys decide, since you'll know what's easiest, can't wait to learn how  to do it though meow. =)

**Comment by samuelm2** [comment]
Discord has been added in a separate pull request. Closing this

**Pull request closed without merging**
